version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: requestweb-mysql
    environment:
      
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} # Mengambil dari file .env
      MYSQL_DATABASE: ${DB_NAME}           # Mengambil dari file .env

    ports:
      - "3306:3306"
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - ./web.sql:/docker-entrypoint-initdb.d/init.sql:z
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 20
  
  

  web:
    build: .
    container_name: requestweb-app
    depends_on:
      db:
        condition: service_healthy

      
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: 'db' # <--- PERBAIKAN KRITIS
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

      DB_PORT: 3306
      JWT_SECRET: ${JWT_SECRET}
      
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  db_data:


