services:
  db:
    image: mysql:8.0
    container_name: requestweb-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: web
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./web.sql:/docker-entrypoint-initdb.d/1-init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 20

  web:
    build: .
    container_name: requestweb-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: ""
      DB_NAME: web
      DB_PORT: 3306
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  db_data:


